version: "3"

services:
  database:
    image: postgres
    volumes:
      - 'database:/var/lib/postgresql/data'
    ports:
      - "32770:5432"
    env_file:
      - .env/development/database.ini
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - .env/development/database.ini
      - .env/development/web.ini
volumes:
  database:
